//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWCFLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoaDBEntities : DbContext
    {
        public SoaDBEntities()
            : base("name=SoaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblSale> tblSales { get; set; }
    
        public virtual int spAddEmployee(Nullable<int> empno, string ename, Nullable<int> mgr)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            var enameParameter = ename != null ?
                new ObjectParameter("ename", ename) :
                new ObjectParameter("ename", typeof(string));
    
            var mgrParameter = mgr.HasValue ?
                new ObjectParameter("mgr", mgr) :
                new ObjectParameter("mgr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddEmployee", empnoParameter, enameParameter, mgrParameter);
        }
    
        public virtual int spDeleteEmployee(Nullable<int> empno)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteEmployee", empnoParameter);
        }
    
        public virtual int spEditEmployee(Nullable<int> empno, string ename, Nullable<int> mgr)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            var enameParameter = ename != null ?
                new ObjectParameter("ename", ename) :
                new ObjectParameter("ename", typeof(string));
    
            var mgrParameter = mgr.HasValue ?
                new ObjectParameter("mgr", mgr) :
                new ObjectParameter("mgr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditEmployee", empnoParameter, enameParameter, mgrParameter);
        }
    
        public virtual ObjectResult<spGetCustomers_Result> spGetCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCustomers_Result>("spGetCustomers");
        }
    
        public virtual ObjectResult<spGetEmployees_Result> spGetEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetEmployees_Result>("spGetEmployees");
        }
    
        public virtual ObjectResult<spGetSales_Result> spGetSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSales_Result>("spGetSales");
        }
    }
}
